config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cars do
    resources :bookings, only: %i[new create]
    collection do
      get :listings
    end
  end
  resources :bookings, only: %i[show edit update destroy index] do
    resources :booking_reviews, only: %i[create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :car
  validates :start_date, presence: true
  validates :end_date, presence: true
  has_many :booking_reviews, dependent: :destroy
end

app/models/booking_review.rb
class BookingReview < ApplicationRecord
  belongs_to :booking

  validates :content, presence: true
  validates :rating, presence: true, numericality: { only_integer: true }, inclusion: { in: (0..5) }
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  geocoded_by :suburb
  after_validation :geocode, if: :will_save_change_to_suburb?

  has_many :bookings, dependent: :destroy
  has_many :booking_reviews, through: :bookings, dependent: :destroy
  has_one_attached :photo

  validates :seats, presence: true
  validates :price, presence: true
  validates :make, presence: true
  validates :model, presence: true
  validates :transmission, presence: true, inclusion: { in: %w[automatic manual] }
  validates :car_type, presence: true
  validates :suburb, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cars
  has_many :bookings
  has_many :bookings_reviews
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/booking_reviews_controller.rb
class BookingReviewsController < ApplicationController
  def create
    review = BookingReview.new(review_params)
    booking = Booking.find(params[:booking_id])
    review.booking = booking
    authorize review
    if review.save
      redirect_to car_path(booking.car)
    else
      (render booking_path(booking))
    end
  end

  def new
    @review = BookingReview.new
    authorize @review
  end

  private

  def review_params
    params.require(:booking_review).permit(:rating, :content)
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[edit update destroy show]
  before_action :set_car, only: %i[new create]

  def index
    @bookings = policy_scope(Booking)
  end

  def new
    @booking = Booking.new
    @booking.car = @car
    authorize @booking
  end

  def create
    booking = Booking.new(booking_params)
    booking.car = @car
    booking.user = current_user
    authorize booking
    if booking.save
      redirect_to booking_path(booking)
    else
      (render new_car_booking_path(@car.id))
    end
  end

  def edit
    authorize @booking
  end

  def update
    authorize @booking
    if @booking.update(booking_params)
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  def show
    @review = BookingReview.new
    authorize @booking
  end

  def destroy
    authorize @booking
    @booking.delete
    redirect_to bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def set_car
    @car = Car.find(params[:car_id])
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: %i[edit update destroy show]

  def index
    @cars = policy_scope(Car)
    @markers = @cars.geocoded.map do |car|
      {
        lat: car.latitude,
        lng: car.longitude
      }
    end
  end

  def new
    authorize Car
    @car = Car.new
  end

  def create
    authorize Car
    car = Car.new(car_params)
    car.user = current_user
    if car.save
      redirect_to car_path(car)
    else
      render :new
    end
  end

  def edit
    authorize @car
  end

  def update
    authorize @car
    if @car.update(car_params)
      redirect_to car_path(@car)
    else
      render :new
    end
  end

  def show
    authorize @car
    @markers =
      [{
        lat: @car.latitude,
        lng: @car.longitude
      }]
      @booking = Booking.new
  end

  def destroy
    authorize @car
    @car.destroy
    redirect_to listings_cars_path
  end

  def listings
    authorize Car
    @cars = Car.where(user: current_user)
    @markers = @cars.geocoded.map do |car|
    {
      lat: car.latitude,
      lng: car.longitude
    }
    end
  end

  private

  def car_params
    params.require(:car).permit(:seats, :price, :make, :model, :transmission, :car_type, :suburb, :photo)
  end

  def set_car
    @car = Car.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_bookingform.html.erb
<%= simple_form_for([car, booking]) do |f| %>
<%= f.input :start_date, label: 'What day would you like to rent the car?'%>
<%= f.input :end_date, label: 'When would you like to return the car?'%>
<div class="form-actions">
    <%= f.button :submit, { class: 'btn btn-primary', id: "bs-btn-primary" } %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<div class="tbanner" style="background-image: url('https://images.unsplash.com/photo-1471479917193-f00955256257?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1931&q=80');">
  <h1>Edit My Booking</h1>
</div>

<div class = "be-container">
  <%= render "bookingform", car: @car, booking: @booking %>
</div>

app/views/bookings/index.html.erb
<div class="padding-top">

<div class="tbanner" style="background-image: url('https://images.unsplash.com/photo-1471479917193-f00955256257?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1931&q=80');">
  <h1>Your Bookings</h1>
</div>

  <div class = "carindexdiv">
    <% @bookings.each do |booking| %>
      <% if booking.car.photo.attached? %>
          <% @url = cl_image_path(booking.car.photo.key, height: 300, crop: :scale) %>
      <% else %>
        <% @url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/No_image_available.svg/2048px-No_image_available.svg.png' %>
      <% end %>
      <div class="card-container">
        <div class="h-50">
          <div class="card" style = "max-width: 24rem;">
            <%= link_to booking_path(booking) do %>
              <img class="card-img-top" src=<%= @url %> alt="Card image cap">
            <% end %>
            <div class="card-body">
              <h5 class="card-title booking-index-card-heading"><%= link_to "#{booking.car.make}, #{booking.car.model}", booking_path(booking) %></h5>
              <p class="card-text booking-index-card-subheading"><%= "Car is booked from: #{booking.start_date}"%></p>
              <p class="card-text booking-index-card-subheading"><%= "Until: #{booking.end_date}"%></p>
            </div>
          </div>
      </div>
    </div>
    <%end %>
  </div>
</div>

app/views/bookings/new.html.erb
<div class = "container">
  <h1>Booking Form</h1>
  <%= render "bookingform", car: @car, booking: @booking %>
</div>

app/views/bookings/show.html.erb
<div class="tbanner" style="background-image: url('https://images.unsplash.com/photo-1471479917193-f00955256257?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1931&q=80');">
  <h1>Details Of Your Booking</h1>
</div>

<div class="bookings-show-container">
  <div class="top-img">
    <% if @booking.car.photo.attached? %>
      <% @url = cl_image_path(@booking.car.photo.key, height: 300, crop: :scale) %>
    <% else %>
      <% @url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/No_image_available.svg/2048px-No_image_available.svg.png' %>
    <% end %>
    <%= image_tag @url, style: 'height:450px;'%>
  </div>

  <div class="bs-heading">
    <h1> <%= @booking.car.make %>, <%= @booking.car.model %></h1>
  </div>

  <div class="date-div">
    <h5>Start Date: <%= @booking.start_date %>, End Date: <%= @booking.end_date %></h5>
  </div>

  <div class="bs-details">
    <div>
      <h4> Type: <%= @booking.car.car_type %> </h4>
      <h4> Location: <%= @booking.car.suburb %></h4>
      <h4>Transmission: <%= @booking.car.transmission %> </h4>
    </div>
    <div>
    <h4>Seats: <%= @booking.car.seats %> </h4>
    <h4>Price per day: $<%= @booking.car.price %> </h4>
    </div>
  </div>

  <div class="bs-btns-div">
    <%= link_to 'Edit', edit_booking_path(@booking.id), class: 'btn btn-primary mb-2', id: "bs-btn-primary" %>
    <%= link_to 'Delete', booking_path(@booking), class: 'btn btn-danger ml-4 mb-2', id: "bs-show-btn-delete", method: 'delete', data: { confirm: "Are you sure?" } %>
  </div>

  <div class="bs-show-car-rating">
    <%= simple_form_for([@booking, @review]) do |f| %>
    <%= f.input :rating, label: 'Rating of the car'%>
    <%= f.input :content, label: 'Thoughts on the car'%>
    <div class="form-actions">
      <%= f.button :submit, { class: 'btn btn-success w-100 create-review' }, { id: "create-review"}%>
    </div>
    <% end %>
  </div>

</div>

app/views/cars/_cars.html.erb
<% cars.each do |car| %>

  <% if car.photo.attached? %>
    <% @url = cl_image_path(car.photo.key, height: 300, crop: :scale) %>
  <% else %>
    <% @url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/No_image_available.svg/2048px-No_image_available.svg.png' %>
  <% end %>

<div class="card-container">
  <%= link_to car_path(car.id) do %>
    <div class="card">
      <div>
        <div class="card-top">
          <img class="card-img-top" src=<%= @url %>>
          <div class="card-heading">
            <h2 class="heading"><%= "#{car.make}, #{car.model}" %></h2>
            <div class="linebreak"></div>
            <p class="subheading"><b><%= "Price: #{car.price}"%></b></p>
          </div>
        </div>
        <div class="car-info">
          <span><i class="fas fa-chair"></i> <%="#{car.seats}"%></span>
          <span><i class="fas fa-cog"></i> <%= "#{car.transmission}"%></span>
          <span><i class="fas fa-compass"></i> <%= "#{car.suburb}"%></span>
        </div>
      </div>
    </div>
  <% end %>
</div>
<% end %>

app/views/cars/_form.html.erb
<%= simple_form_for(car) do |f| %>
<%= f.input :seats, label: 'How many seats does your car have?', class: "listing-input"%>
<%= f.input :price, label: 'How much does your car cost per day?', class: "listing-input"%>
<%= f.input :make, label: 'What make is your car? e.g Holden', class: "listing-input" %>
<%= f.input :model, label: 'What model is your car? e.g Commodore', class: "listing-input"%>
<%= f.input :transmission, label: 'Is your car automatic or manual?', class: "listing-input"%>
<%= f.input :car_type, label: 'What type of car is it? e.g Sedvan/Van', class: "listing-input"%>
<%= f.input :suburb, label: 'Which suburb is your car located in?', class: "listing-input"%>
<%= f.input :photo, as: :file %>
<div class="form-actions">
    <%= f.button :submit, { class: 'btn btn-primary', id: "listing-btn" } %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<div class = "container">
  <h1>Edit Your Car Listing</h1>
  <%= render "form", car: @car %>
</div>

app/views/cars/index.html.erb
<div class="tbanner" style="background-image: url('https://images.unsplash.com/photo-1471479917193-f00955256257?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1931&q=80');">
  <h1>Browse Carental</h1>
</div>

<div class="carindexdiv">
  <%= render "cars", cars: @cars %>
</div>

<div id="map"
     style="width: 100%; height: 500px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

app/views/cars/listings.html.erb
<div class="tbanner" style="background-image: url('https://images.unsplash.com/photo-1471479917193-f00955256257?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1931&q=80');">
  <h1>Your Listed Cars</h1>
</div>

<div class="car-listing-container">
  <%= render "cars", cars: @cars %>
</div>
<div class="create-listing-div">
  <%= link_to "Add a new car", new_car_path, class: "btn btn-primary", id: "bs-btn-primary" %>
</div>

<div id="map"
     style="width: 100%; height: 500px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

app/views/cars/mine.html.erb
<div class="mx-auto" style="width: 400px;">
<% @cars.each do |car| %>
  <h3><%= link_to "#{car.make}, #{car.model}", cars_path(car.id) %></h3>
  <h2><strong><%= car.price %></strong></h2>
  <h4><%= car.suburb %></h4>
  <h4><%= car.seats %></h4>
  <%= link_to "More info",
            cars_path(car.id),
            method: :new,
            data: { confirm: "Are you sure?" } %>
<% end %>
</div>

app/views/cars/new.html.erb
<div class="tbanner" style="background-image: url('https://images.unsplash.com/photo-1471479917193-f00955256257?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1931&q=80');">
  <h1>List Your Car!</h1>
</div>

<div class="listing-form-container">
  <%= render "form", car: @car %>
</div>

app/views/cars/show.html.erb
<div class="tbanner" style="background-image: url('https://images.unsplash.com/photo-1471479917193-f00955256257?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1931&q=80');">
  <h1>Our Cars</h1>
</div>

<div class="car-show-container">
    <div class="top-img">
    <% if @car.photo.attached? %>
      <% @url = cl_image_path(@car.photo.key, height: 300, crop: :scale) %>
    <% else %>
      <% @url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/No_image_available.svg/2048px-No_image_available.svg.png' %>
    <% end %>
    <%= image_tag @url, style: 'height:450px;'%>
  </div>

  <div class="bs-heading">
    <h1> <%= @car.make %> <%= @car.model %></h1>
  </div>

  <div class="bs-details">
    <div>
      <h4>Type: <%= @car.car_type %></h4>
      <h4>Location: <%= @car.suburb %></h4>
      <h4>Transmission: <%= @car.transmission %></h4>
    </div>
    <div>
      <h4>Seats: <%= @car.seats %> </h4>
      <h4>Price per day: $<%= @car.price %> </h4>
    </div>
  </div>

  <div class="bs-show-car-rating">
    <h2>Reviews</h2>
      <%@car.booking_reviews.each do |review| %>
        <div class='bg-white p-3 mb-2'>
          <div class="d-flex justify-content-between border-bottom mb-2 align-items-end">
            <h4><%= review.booking.user.first_name.capitalize %> <%= review.booking.user.last_name.capitalize %></h4>
            <h5>Rating: <%= review.rating %> stars</h4>
          </div>
          <h5>Comment: <%= review.content %></h4>
        </div>
      <% end %>
  </div>

    <div class="booking-box">
      <div class="sticky-top">
      <% if current_user == @car.user %>
        <div style="height: 45vh;" class="overflow-scroll car_card rounded p-3 shadow p-4 mb-5">
          <h2>Bookings</h2>
            <%@car.bookings.each do |booking| %>
              <div class='bg-white p-3 mb-2'>
                <div class="d-flex justify-content-start border-bottom mb-2 align-items-end">
                  <h4><%= booking.user.first_name.capitalize %> <%= booking.user.last_name.capitalize %></h4>
                </div>
                <h5>Start Date: <%= booking.start_date %></h5>
                <h5>End Date: <%= booking.end_date %></h5>
              </div>
            <% end %>
        </div>
      <% else %>
        <div class="bg-white car_card rounded p-3 p-4 mb-2">
          <%= simple_form_for([@car, @booking]) do |f| %>
            <%= f.input :start_date, label: 'What day would you like to rent the car?'%>
            <%= f.input :end_date, label: 'When would you like to return the car?'%>
            <div class="form-actions">
              <%= f.button :submit, { class: 'btn btn-primary w-100 bs-btn-primary', id: "bs-btn-primary" } %>
            </div>
          <% end %>
        </div>
      <% end %>
      <div class='px-4'>
        <% if current_user == @car.user %>
          <%= link_to 'Back', listings_cars_path, class: 'btn btn-primary mb-2 w-100', id: "bs-btn-primary" %>
        <% else %>
          <%= link_to 'Back', cars_path, class: 'btn btn-primary mb-2 w-100', id: "bs-btn-primary" %>
        <% end %>
      </div>
    </div>
      </div>
  </div>

  <% if current_user == @car.user %>
    <div class="d-flex justify-content-around">
      <%= link_to 'Edit', edit_car_path(@car.id), class: 'btn btn-primary mb-2 w-25', id: "bs-btn-primary" %>
      <%= link_to 'Delete', car_path(@car.id), class: 'btn btn-danger ml-4 mb-2 w-25', id: "bs-show-btn-delete", method: 'delete', data: { confirm: "Are you sure?" } %>
    </div>
  <% end %>

</div>
<div id="map"
     style="width: 100%; height: 40vh;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_pack_tag 'application' %>
    <title>Carental</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&display=swap');
    </style>
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Merriweather&family=Roboto:wght@400;500&display=swap');
    </style>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.4/css/fontawesome.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>
  <link
   rel="stylesheet"
   href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css"
   integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog=="
   crossorigin="anonymous"
  />
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Merriweather:wght@700&display=swap');
  </style>
  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

    <%# <p class="alert"><%= alert %>
    <%# <p class="notice"><%= notice %>

app/views/pages/home.html.erb
<div class="home-container">
  <div class="banner" style="background-image: url('https://images.unsplash.com/photo-1471479917193-f00955256257?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1931&q=80');">
    <p>USA's Easiest Car Rental Service</p>
    <h1>CARENTAL</h1>
    <div class="sbar-container">
      <i class="fas fa-search"></i>
      <input aria-label="search" type="search" placeholder= "Search Carental" class="searchbar" value="">
    </div>

    <div class="seperator">
      <div class="lineleft"></div>
      <span class="ortext">OR</span>
      <div class="lineright"></div>
    </div>

    <a><%= link_to "RENT A CAR", cars_path, class: "orange-buttons" %></a>
    <a><%= link_to "MANAGE MY LISTINGS", listings_cars_path, class: "orange-buttons" %></a>
  </div>
</div>

app/views/pages/index.htm.erb
<h1>All cars from database</h1>


<% @index.each do |car| %>
  <h3><%= link_to("#{car.make}, #{car.model}", new_rent_path(car.id)) %></h3>
  <h2><strong><%= car.price %></strong></h2>
  <h4><%= car.suburb %></h4>
  <h4><%= car.seats %></h4>
  <%= link_to "More info",
            new_rent_path(car.id),
            method: :new,
            data: { confirm: "Are you sure?" } %>
<% end %>
<br>
<br>
<%= link_to "Rent this car", new_rent_path %>

app/views/shared/_footer.html.erb
<div class="footer">
  <span>© 2021 Carental, All rights reserved</span>
  <ul class="footer-items">
    <a href="">Privacy</a>
    <a href="">Terms</a>
    <a href="">Site Map</a>
  </ul>
</div>

app/views/shared/_navbar.html.erb
<nav>
      <ul class="nav-links">
        <li>
          <%= link_to "Browse", cars_path%>
        </li>
        <li >
          <%= link_to "My Bookings", bookings_path%>
        </li>
        <li >
          <%= link_to "List My Car", new_car_path%>
        </li>
        <li >
          <%= link_to "Home", root_path%>
        </li>
        <li >
          <%= link_to "My Listings", listings_cars_path%>
        </li>

        <% if user_signed_in?  %>
          <li id="btn-log-in"><%= link_to "Sign Out", destroy_user_session_path, method: :delete%></li>
        <% else  %>
          <li id="btn-sign-up"><%= link_to "Sign Up", new_user_registration_path %></li>
          <li id="btn-log-in"><%= link_to "Log In", user_session_path %></li>
        <% end %>
      </ul>

      <div class="burger">
        <div class="line1"></div>
        <div class="line2"></div>
        <div class="line3"></div>
      </div>
</nav>

app/views/shared/temp.html.erb
<nav class="navbar navbar-dark bg-transparent">
    <h2><%= link_to "Carental", root_path %></h2>
      <div class="login-form">
        <% if user_signed_in?  %>
          <li id="btn-log-in"><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% else  %>
          <li id="btn-sign-up"><%= link_to "Sign Up", new_user_registration_path %></li>
          <li id="btn-log-in"><%= link_to "Log In", user_session_path %></li>
        <% end %>
      </div>
  </div>
</nav>

<nav class="navbar navbar-expand-lg navbar-dark bg-transparent">
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="#">1st page <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="#">2rd page</a>
      <a href="#"><%= link_to "1st page", cars_path, class: "btn btn-primary" %></a>
    </div>
    <a class="navbar-brand" href="#">Carental</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    <div class="navbar-nav">
      <a class="nav-item nav-link" href="#">3rd page</a>
      <a class="nav-item nav-link" href="#">4th page</a>
    </div>
  </div>
</nav>